import type { Metadata } from "next";
import { Geist, Geist_Mono, Explora, Montserrat } from "next/font/google";
import "./globals.css";
import { SmoothCursor } from "@/components/magicui/smooth-cursor";
import { InteractiveGridPattern } from "@/components/ui/interactive-grid-pattern";
import { BottomDock } from "@/components/bottom-dock";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const explora = Explora({
  weight: "400",
  variable: "--font-explora",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${explora.variable} ${montserrat.variable} antialiased cursor-none`}
      >
        <InteractiveGridPattern
          proximity={200}
          borderColor="rgba(0, 221, 255, 0.05)"
        >
          <SmoothCursor />
          {children}
          <div className="fixed top-6 left-0 right-0 z-50 pointer-events-none flex justify-center">
            <div className="pointer-events-auto">
              <BottomDock />
            </div>
          </div>
        </InteractiveGridPattern>
      </body>
    </html>
  );
}
