create table if not exists public.contact_inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  project_type text not null,
  message text not null,
  source text not null default 'contact-page',
  created_at timestamp with time zone not null default now()
);

alter table public.contact_inquiries
  add column if not exists id bigint generated by default as identity;

alter table public.contact_inquiries
  add column if not exists name text;

alter table public.contact_inquiries
  add column if not exists email text;

alter table public.contact_inquiries
  add column if not exists project_type text;

alter table public.contact_inquiries
  add column if not exists message text;

alter table public.contact_inquiries
  add column if not exists source text;

alter table public.contact_inquiries
  add column if not exists created_at timestamp with time zone;

alter table public.contact_inquiries
  alter column name set not null;

alter table public.contact_inquiries
  alter column email set not null;

alter table public.contact_inquiries
  alter column project_type set not null;

alter table public.contact_inquiries
  alter column message set not null;

alter table public.contact_inquiries
  alter column source set default 'contact-page';

update public.contact_inquiries
set source = 'contact-page'
where source is null;

alter table public.contact_inquiries
  alter column source set not null;

update public.contact_inquiries
set created_at = now()
where created_at is null;

alter table public.contact_inquiries
  alter column created_at set default now();

alter table public.contact_inquiries
  alter column created_at set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.contact_inquiries'::regclass
      and contype = 'p'
  ) then
    alter table public.contact_inquiries
      add constraint contact_inquiries_pkey primary key (id);
  end if;
end $$;

create index if not exists contact_inquiries_created_at_idx
  on public.contact_inquiries (created_at desc);

alter table public.contact_inquiries enable row level security;

drop policy if exists "Allow public contact inserts" on public.contact_inquiries;

create policy "Allow public contact inserts"
  on public.contact_inquiries
  for insert
  to anon, authenticated
  with check (true);
