create table if not exists public.mimesis_waitlist (
  id bigint generated by default as identity primary key,
  email text not null,
  source text not null default 'mimesis',
  created_at timestamp with time zone not null default now()
);

alter table public.mimesis_waitlist
  add column if not exists id bigint generated by default as identity;

alter table public.mimesis_waitlist
  add column if not exists email text;

alter table public.mimesis_waitlist
  add column if not exists source text;

alter table public.mimesis_waitlist
  add column if not exists created_at timestamp with time zone;

alter table public.mimesis_waitlist
  alter column email set not null;

alter table public.mimesis_waitlist
  alter column source set default 'mimesis';

update public.mimesis_waitlist
set source = 'mimesis'
where source is null;

alter table public.mimesis_waitlist
  alter column source set not null;

update public.mimesis_waitlist
set created_at = now()
where created_at is null;

alter table public.mimesis_waitlist
  alter column created_at set default now();

alter table public.mimesis_waitlist
  alter column created_at set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.mimesis_waitlist'::regclass
      and contype = 'p'
  ) then
    alter table public.mimesis_waitlist
      add constraint mimesis_waitlist_pkey primary key (id);
  end if;
end $$;

create unique index if not exists mimesis_waitlist_email_key
  on public.mimesis_waitlist (email);

alter table public.mimesis_waitlist enable row level security;

drop policy if exists "Allow public waitlist inserts" on public.mimesis_waitlist;

create policy "Allow public waitlist inserts"
  on public.mimesis_waitlist
  for insert
  to anon, authenticated
  with check (true);
